#!/bin/bash

#
# This script starts IPC server, account generator, etc.
#

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

if ! [ -d "./user_instances" ]; then
	echo "You need to run install-catbots first."
	exit
fi

sudo mkdir -p /opt/steamapps
mountpoint -q /opt/steamapps || sudo mount --bind ~/.steam/steam/steamapps/ /opt/steamapps

ipcserver=$( ps faux | grep '/opt/cathook/ipc/bin/server' | grep -vw grep | awk '{ print $2 }' );
[ -z "$ipcserver" ] && /opt/cathook/ipc/bin/server -s >/dev/null &
[ -z "$ipcserver" ] && echo $! >/tmp/cat-ipc-server.pid

if [ -e "/tmp/ncat-cathook-webpanel.pid" ] && ps -p `cat "/tmp/ncat-cathook-webpanel.pid"` >/dev/null; then
    echo IPC panel already running.
else
    pushd rosnehook-ipc-web-panel
    sudo PATH="$PATH" STEAM_LD_PRELOAD="$(cd ../ && pwd)/just-disable-vac/build/bin64/libvpcfs.so.0:$(cd ../ && pwd)/just-disable-vac/build/bin32/libvpcfs.so.0" bash ./run.sh &
    popd
fi

if [ -x "$(command -v pulseaudio)" ]; then
    echo "Setting up micspam..."
    pulse=$(pgrep -u "$USER" pulseaudio);
    ([ ! -z "$pulse" ]) && pulseaudio --start &>/dev/null &
    pactl load-module module-null-sink
    echo
    echo "Null sink has been loaded!"
fi

sleep 5;

echo "IPC Web Panel password: `cat /tmp/cat-webpanel-password`"
echo "Fixing NVIDIA crash"
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg

echo "Open a web browser and go to localhost:8081 to see your Rosnehook IPC web panel."
