#!/usr/bin/env bash
read -p "Press ENTER to continue"

echo "Removing legacy..."

./remove-legacy

rm -rf ./build
rm -rf ./temprosnehook
rm -rf ./rosnehook-ipc-server
rm -rf ./rosnehook-ipc-web-panel
rm -rf ./just-disable-vac
rm -rf ./user_instances
rm -rf ./rosnebot-database
sudo rm -rf /opt/cathook/ipc
sudo rm /opt/cathook/bin/libcathook-textmode.so
